Add missing unistd.h in src/main.cpp
Fixes: main.cpp: error: getpid was not declared in this scope

Bug: https://bugs.gentoo.org/967521
Signed-off-by: Andreas Sturmlechner <asturm@gentoo.org>